[package]
name = "luar"
version = "0.1.0"
authors = ["Yaroslav <q.link0.p@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "1.0"
logos = "0.11"
thiserror = "1.0"
num = "0.3"
regex = "1.4"

[dev-dependencies]
insta = "1.3"
function_name = "0.2"
quickcheck = "0.9.2"
quickcheck_macros = "0.9.1"
