[package]
name = "test_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luar_lex = { path = "../luar_lex" }
lazy_static = "1.4.0"
num = "0.4"
quickcheck = "1.0"
